In [7]:
import pandas as pd

In [8]:
ventas = pd.read_csv('ventas.csv')
ventas.head()

   id_venta       fecha  producto  cantidad  precio_unitario
0         1  2026-01-10  Notebook         2             1200
1         2  2026-01-12     Mouse         5               25
2         3  2026-01-15   Teclado         3               45
3         4  2026-01-18   Monitor         1              300

In [9]:
clientes = pd.read_json('clientes.json')
len(clientes)

3

In [10]:
inventario = pd.read_excel('inventario.xlsx')
inventario.head()

   id_producto    nombre    categoria  stock  precio
0            1  Notebook  Electrónica     10    1200
1            2     Mouse   Accesorios     50      25
2            3   Teclado   Accesorios     30      45
3            4   Monitor  Electrónica     15     300

In [11]:
inventario['stock'].mean()

np.float64(26.25)